name: "Test"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Test against PHP ${{ matrix.php-version }} Symfony ${{ matrix.symfony-version }}
    strategy:
      matrix:
        php-version: [ '8.0', '8.1', '8.2', '8.3' ]
        symfony-version: [ '^5.0', '^6.0', '^7.0' ]

    steps:
      - uses: actions/checkout@v4
      - run: cp .github/devenv/devenv_${{ matrix.php-version }}.local.nix ./devenv.local.nix
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Install the dependencies 🔧
        run: |
          rm composer.lock
          devenv shell composer config extra.symfony.require "${{ matrix.symfony-version }}"
          devenv shell composer install -- --prefer-dist --no-interaction --no-progress

      - name: Dump versions
        run: |
          devenv shell dump-versions

      - name: Execute the tests 🔧
        run: devenv test

      # - name: Upload results to Codeclimate 🚀
      #   uses: paambaati/codeclimate-action@v8.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      #   with:
      #     coverageLocations: |
      #       ${{ github.workspace }}/reports/clover.xml:clover

      - name: Upload results to Codecov 🚀
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./reports/clover.xml
          verbose: true
